export const stockList: string[] = [
    'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'GOOG', 'NVDA', 'META', 'TSLA', 'BRK.B', 'LLY',
    'JPM', 'JNJ', 'V', 'XOM', 'UNH', 'WMT', 'MA', 'PG', 'CVX', 'COST',
    'HD', 'MRK', 'AVGO', 'ABBV', 'PEP', 'KO', 'PFE', 'BAC', 'CRM', 'ADBE',
    'NFLX', 'CSCO', 'CCE', 'CMCSA', 'DHR', 'VZ', 'TMO', 'MCD', 'UNP', 'BMY',
    'WFC', 'BA', 'AMGN', 'TXN', 'ACN', 'HON', 'RTX', 'QCOM', 'T', 'ORCL',
    'SBUX', 'CVS', 'MS', 'GS', 'PM', 'INTU', 'AMAT', 'CAT', 'GE', 'MRNA',
    'BLK', 'LIN', 'GM', 'DELL', 'TGT', 'KLAC', 'AXP', 'ISRG', 'CMG', 'ADP',
    'TMUS', 'PANW', 'REGN', 'BKNG', 'SHW', 'GILD', 'CI', 'SYK', 'ITW', 'PGR',
    'SO', 'DUK', 'ADI', 'ETN', 'CCI', 'EQIX', 'COF', 'PNC', 'CSX', 'COP',
    'SLB', 'MMC', 'EOG', 'FCX', 'SRE', 'DE', 'F', 'SCHW', 'ELV', 'CSGP',
    'FIS', 'MU', 'GD', 'NOC', 'LOW', 'SPG', 'DLR', 'PLD', 'PSA', 'NEE',
    'D', 'AEP', 'EIX', 'XEL', 'FE', 'DTE', 'PCG', 'CNP', 'EVRG', 'AEE',
    'NI', 'WEC', 'CMS', 'AES', 'NRG', 'ED', 'KMI', 'LNG', 'WMB', 'OKE',
    'ET', 'MPLX', 'EQT', 'DVN', 'OXY', 'MRO', 'VLO', 'PSX', 'BKR', 'HAL',
    'PAGP', 'EPD', 'MMP', 'PAA', 'TRGP', 'ACGL', 'AFL', 'MET', 'PRU',
    'TRV', 'CB', 'WTW', 'AJG', 'L', 'AIG', 'CBOE', 'NDAQ', 'ICE', 'SPGI',
    'MCO', 'FDS', 'VRSK', 'TRU', 'EQF', 'DNB', 'EXPN', 'FNF', 'FAF', 'CLGX',
    'RP', 'ZG', 'Z', 'RDFN', 'OPEN', 'OPAD', 'RKT', 'LEND', 'UPST', 'SOFI',
    'AFRM', 'COIN', 'HOOD', 'SQ', 'PYPL', 'FISV', 'GPN', 'VFI', 'NCR', 'DBD',
    'BKS', 'ALLE', 'SWK', 'CARR', 'OTIS', 'TT', 'IR', 'DOV', 'FTV', 'RHI',
    'XYL', 'PNR', 'EWTX', 'VNT', 'IEX', 'FLOW', 'GWW', 'NDSN', 'PH', 'EMR',
    'JCI', 'AOI', 'RS', 'NUE', 'STLD', 'CLF', 'X', 'WOR', 'CMC', 'RYI',
    'MLI', 'CRS', 'HAYN', 'ATI', 'TMST', 'USAP', 'HWM', 'ARNC', 'KALU', 'GTN',
    'CSTM', 'CENX', 'AA', 'RIO', 'BHP', 'VALE', 'SCCO', 'GOLD', 'NEM', 'AGI',
    'KGC', 'GFI', 'SSW', 'AU', 'HMY', 'AUY', 'CDE', 'PAAS', 'AG',
    'EXK', 'FSM', 'HL', 'SSR', 'VGCX', 'BTO', 'KL', 'OR', 'FNV', 'WPM',
    'RGLD', 'SAND', 'MTA', 'GPMLF', 'NGD', 'ARNGF', 'DPM', 'PVG', 'EQX', 'CXB',
    'ASM', 'GAU', 'MCEAF', 'AEM', 'OGC', 'CG', 'ELD', 'LUG', 'CDNLF', 'WAFR', 
    'RSM', 'NST', 'EVN', 'SBM', 'SAR', 'RML', 'GRR', 'RRS', 'SLR'
];